import { StyleSheet } from "react-native";

// Estilos para o tema escuro
export const darkStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0D1B2A",
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 240,
    height: 240,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#00FF99",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 30,
  },
  inputContainer: {
    width: "100%",
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    color: "#00FF99",
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: "#0D1B2A",
    borderWidth: 2,
    borderColor: "#00FF99",
    borderRadius: 8,
    padding: 12,
    color: "#FFFFFF",
    width: "100%",
  },
  button: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#00FF99",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 20,
    width: "80%",
    alignItems: "center",
  },
  buttonText: {
    color: "#00FF99",
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#00FF99",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 15,
    width: "80%",
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#00FF99",
    fontSize: 16,
  },
  linkText: {
    color: "#00FF99",
    fontSize: 16,
    textDecorationLine: "underline",
    marginTop: 15,
    marginBottom: 15,
  },
  tipText: {
    fontSize: 14,
    color: "#AAAAAA",
    textAlign: "center",
    marginTop: 20,
    fontStyle: "italic",
  },
  codeInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginBottom: 20,
  },
  codeInput: {
    width: 45,
    height: 50,
    borderWidth: 2,
    borderColor: "#00FF99",
    borderRadius: 8,
    textAlign: "center",
    fontSize: 20,
    color: "#FFFFFF",
    backgroundColor: "#0D1B2A",
  },
  messageBox: {
    backgroundColor: "#162B3D",
    borderRadius: 8,
    padding: 15,
    width: "100%",
    marginBottom: 20,
  },
  messageText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginBottom: 10,
  },
  codeContainer: {
    backgroundColor: "#162B3D",
    borderRadius: 8,
    padding: 15,
    width: "80%",
    alignItems: "center",
    marginVertical: 20,
  },
  codeText: {
    color: "#00FF99",
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  errorText: {
    color: "#FF6B6B",
    fontSize: 14,
    marginTop: 5,
  },
});

// Estilos para o tema claro
export const lightStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 240,
    height: 240,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#00AA66",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#333333",
    textAlign: "center",
    marginBottom: 30,
  },
  inputContainer: {
    width: "100%",
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    color: "#00AA66",
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: "#F5F5F5",
    borderWidth: 2,
    borderColor: "#00AA66",
    borderRadius: 8,
    padding: 12,
    color: "#333333",
    width: "100%",
  },
  button: {
    backgroundColor: "#00AA66",
    borderWidth: 0,
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 20,
    width: "80%",
    alignItems: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#00AA66",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 15,
    width: "80%",
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#00AA66",
    fontSize: 16,
  },
  linkText: {
    color: "#00AA66",
    fontSize: 16,
    textDecorationLine: "underline",
    marginTop: 15,
    marginBottom: 15,
  },
  tipText: {
    fontSize: 14,
    color: "#777777",
    textAlign: "center",
    marginTop: 20,
    fontStyle: "italic",
  },
  codeInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginBottom: 20,
  },
  codeInput: {
    width: 45,
    height: 50,
    borderWidth: 2,
    borderColor: "#00AA66",
    borderRadius: 8,
    textAlign: "center",
    fontSize: 20,
    color: "#333333",
    backgroundColor: "#F5F5F5",
  },
  messageBox: {
    backgroundColor: "#F0F0F0",
    borderRadius: 8,
    padding: 15,
    width: "100%",
    marginBottom: 20,
  },
  messageText: {
    color: "#333333",
    fontSize: 16,
    marginBottom: 10,
  },
  codeContainer: {
    backgroundColor: "#F0F0F0",
    borderRadius: 8,
    padding: 15,
    width: "80%",
    alignItems: "center",
    marginVertical: 20,
  },
  codeText: {
    color: "#00AA66",
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 14,
    marginTop: 5,
  },
});
